### ISSUE TITLE
Bad behavior if current progress bar is longer than terminal is wide

### ISSUE THREAD

**Issue by antifuchs** [emersonford/tracing-indicatif#1] opened 2023-02-28 20:31 UTC
Really love using tracing-indicatif - ever since adding it in antifuchs/deploy-flake#177. Unfortunately, I'm noticing one weird behavior in terminal windows that can't fit the entirety of a progress line: If multiple spans are active, and the parent span has a progress spinner, instead of getting updated in-place, it scrolls away.

This is probably easier to show in a video than to explain in words:

https://user-images.githubusercontent.com/11864/221971195-0c8131e3-c56f-4995-8622-24a27e9d6194.mov

As you can see there, the "build" span is actively working (and it's longer than the terminal is wide), and every time the progress spinner ticks forward, the parent span's progress bar scrolls off by one line. 

If I make the terminal wide enough to fit the line, that behavior stops; but it would be nice if tracing-indicatif could accommodate tighter spaces better.

**Comment by emersonford** [comment] 2023-03-01 04:16
I'm fairly certain the root cause here is a bug in indicatif as your video looks almost identical to console-rs/indicatif#520 and console-rs/indicatif#496, and indicatif handles all the logic for redrawing progress bars in this library, so we might need to wait for indicatif to fix it unfortunately.

I'm trying to think of ways to solve this from `tracing-indicatif` in the mean time and am coming up blank. =/ One option would be to truncate the keys/message of the progress bar, but indicatif (afaik) provides no API to determine the "length" of all the keys/messages in the progress bar, so there's no way to determine if we're going to overflow the terminal line or not. If I think of anything (or can think of a PR to solve this in indicatif), will update :)

**Comment by antifuchs** [comment] 2023-03-01 07:18
Ah! That makes a ton of sense. Thanks for digging those up, I did only a cursory search before submitting here. Handling all this in indicatif sounds like the right spot!

**Comment by emersonford** [comment] 2023-04-27 04:28
fyi this issue should be fixed with https://github.com/console-rs/indicatif/pull/533. :) looks like it just needs a contributor to merge it at this point.

**Comment by emersonford** [comment] 2023-08-21 22:45
marking as closed since it's fixed on the indicatif side

**Closed by emersonford** 2023-08-21 22:45 UTC
